name: application-build 

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install panda
        run: python3 -m pip install -r requirements.txt

      - name: build
        run: python setup.py bdist_apps 

      - uses: actions/upload-artifact@v3
        with:
          name: DarkMatterMage_Win
          path: ./dist/Dark\ Matter\ Mage-0.0.0_win_amd64.zip 

      - uses: actions/upload-artifact@v3
        with:
          name: DarkMatterMage_Linux
          path: ./dist/Dark\ Matter\ Mage-0.0.0_manylinux2010_x86_64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: DarkMatterMage_OSX
          path: ./dist/Dark\ Matter\ Mage-0.0.0_macosx_10_9_x86_64.zip 